### ISSUE TITLE
[BUG] ETIMEDOUT errors are not handled & retried

### ISSUE THREAD

**Issue by piotrFalkowskiIt** [rodrigozr/sqs-grep#5]
**Describe the bug**
I can't find in code  error handling / retrying of failed request to sqs api. 
sqs-grep just exit after failed request to sqs api. 
It has failed for me, after dumping  around 9000 of messages - 3 times already. 
`sqs-grep --queue QUEUE_URL --all --outputFile file.txt --full -j 3 -t 600
Connecting to SQS queue URL QUEUE_URL ...
This queue has approximately 44103 messages at the moment.
Will match ALL messages in the queue.
Scanning...
Error: connect ETIMEDOUT AMAZON_REGION_ENDPOINT_IP:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)`

**To Reproduce**
1. Create a queue 'X' with thousands of messages
2. Run sqs-grep with arguments 
sqs-grep --queue QUEUE_URL --all --outputFile file.txt --full -j 3 -t 600
3. See error

**Expected behavior**
Calls to sqs api should be retried for example 3 times with some backof time. 

**Desktop (please complete the following information):**
 - OS: Windows 
 - Version Windows 10

**Comment by rodrigozr** [comment]
The official AWS SDK is supposed to transparently handle retries, but the number of retries is "automatically calculated per service", so it is hard to tell what exactly it is doing for SQS calls.

I'll probably just add a new `--maxRetries` argument with a default value of `3` to give users a more predictable and controllable behavior at the same time.

**Comment by rodrigozr** [comment]
Hello @piotrFalkowskiIt, can you please test with the latest version? I added `--maxRetries` and `--verbose` options which should help with that
